FROM tensorflow/tensorflow:nightly-gpu-jupyter
MAINTAINER cjgo

RUN apt-get update
RUN pip install opencv-python
RUN pip install matplotlib
RUN pip install pandas
RUN pip install seaborn
RUN pip install plotly==4.7.1
RUN pip install pillow
